package whaleFacts

import (
	"math/rand"
)

func GenerateWhaleFact() string {
	// Generated by chat-gpt Mar 26 2023
	facts := []string{
		"Whales are mammals, not fish.",
		"There are two types of whales: baleen whales and toothed whales.",
		"Baleen whales have bristly plates in their mouths that they use to filter food from the water.",
		"Toothed whales use their teeth to catch and eat fish, squid, and other marine creatures.",
		"Blue whales are the largest animals on Earth, growing up to 100 feet long.",
		"The heart of a blue whale is about the size of a small car.",
		"Some whale species can communicate with each other over hundreds of miles.",
		"Whales can hold their breath for a long time - up to 90 minutes in some cases.",
		"Humpback whales are known for their songs, which can last for 20 minutes or more.",
		"Bowhead whales are the longest-living mammals on Earth, with some individuals living over 200 years.",
		"Gray whales undertake one of the longest migrations of any mammal, traveling up to 12,000 miles each year.",
		"Whales are important to the ocean ecosystem, helping to regulate the food chain and carbon cycle.",
		"Whaling, the hunting of whales for their meat, oil, and other products, has drastically reduced whale populations over the last several centuries.",
		"Some whale species, such as the humpback whale, are known for their acrobatic displays, such as breaching and tail-slapping.",
		"The blue whale's tongue alone can weigh as much as an elephant.",
		"Killer whales, also known as orcas, are actually members of the dolphin family.",
		"Humpback whales are known to form close bonds with other individuals, and have been observed protecting seals and other marine creatures from predators.",
		"A group of whales is called a pod.",
		"The narwhal, a type of toothed whale, has a long, spiral tusk that can grow up to 10 feet long.",
		"Whales are warm-blooded, which means they can maintain a constant body temperature regardless of the temperature of the water they're swimming in.",
		"Sperm whales have the largest brains of any animal on Earth, weighing up to 20 pounds.",
		"Humpback whales are found in every ocean in the world.",
		"Some whale species, such as the minke whale, can swim at speeds of up to 20 miles per hour.",
		"Whales are protected under international law, with hunting and killing of whales banned in most countries.",
		"The fin whale, the second-largest animal on Earth, can grow up to 85 feet long.",
		"Whale songs are complex and can last for hours.",
		"Gray whales are bottom-feeders, sucking up sediment from the ocean floor and filtering out small crustaceans.",
		"The beluga whale is also known as the 'sea canary' because of its vocalizations.",
		"Humpback whales are one of the most studied whale species, with researchers using photo identification, genetic analysis, and acoustic monitoring to track their movements and behavior.",
		"Whale sharks, which are the largest fish in the ocean, are not actually whales.",
		"Bowhead whales are adapted to live in the Arctic and have a thick layer of blubber to keep them warm.",
		"Sperm whales are the deepest-diving whales, able to reach depths of up to 7,000 feet.",
		"Gray whales are known for their friendliness towards humans and have been observed approaching boats and even allowing people to pet them.",
		"The blue whale's heart beats only"}

	return facts[rand.Intn(len(facts))]
}
